export default [
  {
    name: "Annoy-o-Tron",
    species: ["Mech"],
    attack: 1,
    health: 2,
    keywords: ["Taunt", "Divine Shield"],
    minions: [],
    picture: "pics/Annoy-o-Tron.png",
  },
  {
    name: "Beleaguered Battler",
    species: [],
    attack: 4,
    health: 5,
    keywords: [],
    minions: [],
    picture: "pics/Beleaguered Battler.png",
  },
  {
    name: "Emerald Proto-Whelp",
    species: ["Dragon"],
    attack: 1,
    health: 4,
    keywords: [],
    minions: [],
    picture: "pics/Emerald Proto-Whelp.png",
  },
  {
    name: "Harmless Bonehead",
    species: ["Undead"],
    attack: 0,
    health: 2,
    keywords: ["Deathrattle"],
    minions: [
      {
        name: "Harmless Bonehead",
        minionName: "Sceleton",
        attack: 1,
        health: 1,
      },
      {
        name: "Harmless Bonehead",
        minionName: "Sceleton",
        attack: 1,
        health: 1,
      },
    ],
    picture: "pics/Harmless Bonehead.png",
  },
  {
    name: "Imprisoner",
    species: ["Demon"],
    attack: 3,
    health: 2,
    keywords: ["Taunt", "Deathrattle"],
    minions: [{ name: "Imprisoner", minionName: "Imp", attack: 1, health: 1 }],
    picture: "pics/Imprisoner.png",
  },
  {
    name: "Manasaber",
    species: ["Beast"],
    attack: 4,
    health: 1,
    keywords: ["Deathrattle"],
    minions: [
      {
        name: "Manasaber",
        minionName: "Cubling",
        attack: 0,
        health: 1,
      },
      {
        name: "Manasaber",
        minionName: "Cubling",
        attack: 0,
        health: 1,
      },
    ],
    picture: "pics/Manasaber.png",
  },
  {
    name: "Micro Mummy",
    species: ["Mech", "Undead"],
    attack: 1,
    health: 2,
    keywords: ["Reborn"],
    minions: [
      {
        name: "Micro Mummy",
        minionName: "Micro Mummy Reborn",
        attack: 1,
        health: 1,
      },
    ],
    picture: "pics/Micro Mummy.png",
  },
  {
    name: "Razorfen Geomancer",
    species: ["Quilboar"],
    attack: 4,
    health: 2,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Razorfen Geomancer.png",
  },
  {
    name: "Refreshing Anomaly",
    species: ["Elemental"],
    attack: 1,
    health: 4,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Refreshing Anomaly.png",
  },
  {
    name: "Risen Rider",
    species: ["Undead"],
    attack: 2,
    health: 1,
    keywords: ["Taunt", "Reborn"],
    minions: [
      {
        name: "Risen Rider",
        minionName: "Risen Rider Reborn",
        attack: 2,
        health: 1,
      },
    ],
    picture: "pics/Risen Rider.png",
  },
  {
    name: "Rockpool Hunter",
    species: ["Murloc"],
    attack: 2,
    health: 3,
    keywords: ["Battlelcry"],
    minions: [],
    picture: "pics/Rockpool Hunter.png",
  },
  {
    name: "Scallywag",
    species: ["Pirate"],
    attack: 3,
    health: 1,
    keywords: ["Deathrattle"],
    minions: [
      {
        name: "Scallywag",
        minionName: "Pirate",
        attack: 1,
        health: 1,
      },
    ],
    picture: "pics/Scallywag.png",
  },
  {
    name: "Sellemental",
    species: ["Elemental"],
    attack: 2,
    health: 2,
    keywords: ["Text"],
    minions: [],
    picture: "pics/Sellemental.png",
  },
  {
    name: "Shell Collector",
    species: ["Naga"],
    attack: 2,
    health: 1,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Shell Collector.png",
  },
  {
    name: "Southsea Busker",
    species: ["Pirate"],
    attack: 3,
    health: 1,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Southsea Busker.png",
  },
  {
    name: "Sun-Bacon Relaxer",
    species: ["Quilboar"],
    attack: 1,
    health: 2,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Sun-Bacon Relaxer.png",
  },
  {
    name: "Surf n' Surf",
    species: ["Beats", "Naga"],
    attack: 1,
    health: 1,
    keywords: ["Deathrattle"],
    minions: [
      {
        name: "Surf n' Surf",
        minionName: "Crab",
        attack: 3,
        health: 2,
      },
    ],
    picture: "pics/Surf n' Surf.png",
  },
  {
    name: "Swampstriker",
    species: ["Murloc"],
    attack: 1,
    health: 5,
    keywords: ["Text"],
    minions: [],
    picture: "pics/Swampstriker.png",
  },
  {
    name: "Upbeat Frontdrake",
    species: ["Dragon"],
    attack: 1,
    health: 1,
    keywords: ["Text"],
    minions: [],
    picture: "pics/Upbeat Frontdrake.png",
  },
  {
    name: "Wrath Weaver",
    species: [],
    attack: 1,
    health: 4,
    keywords: ["Text"],
    minions: [],
    picture: "pics/Beleaguered Battler.png",
  },
  {
    name: "Picky Eater",
    species: ["Demon"],
    attack: 1,
    health: 1,
    keywords: ["Battlecry"],
    minions: [],
    picture: "pics/Picky Eater.png",
  },
];
